package lessons.oop;

class MyClass {
        
    public String toString() {
            return "Hello";
        }
}
public class ObjectDemo { // Every class inherits Object class by default, Object is the superclass of all class
    public static void main(String[] args) {
        Object obj = new Object();
        MyClass my = new MyClass();

        System.out.println(my.toString());

        System.out.println(obj.getClass());
        System.out.println(obj.hashCode()); // unique id generated by java for each new object
        System.out.println(obj.equals(obj));
        System.out.println(obj.toString());
        
        
    }
    
}

